version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backing-services
    depends_on:
      - mongo_db
      - activemq
  mongo_db:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backing-services
  activemq:
    image: "rmohr/activemq"
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    networks:
      - backing-services

networks:
  backing-services:
    driver: bridge

